---
- name: Setup Vprofile bastion host
  hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Import VPC setup variable
      include_vars: vars/vpc_setup
    - name: import VPC setup variable
      include_vars: vars/output_vars

    - name: Create vprofile ec2 key
      ec2_key:
        name: vprofile-key
        region: "{{region}}"
      register: key_out

    - name: Save private key into file bastion-key.pem
      copy:
        content: "{{key_out.key.private_key}}"
        dest: "./bastion-key.pem"
        mode: 0600
      when: key_out.changed

    - name: Create sec grp for bastion host
      ec2_group:
        name: bastion-host-sg
        description: "Allow port 22 from everywhere and all port within sg"
        region: "{{region}}"
        vpc_id: "{{vpcid}}"
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: "{{myip}}"
      register: BastionSG_out
    - name: Creating Bastion host
      amazon.aws.ec2_instance:
        key_name: vprofile-key
        region: "{{region}}"
        instance_type: t2.micro
        image_id: "{{bastion_ami}}"
        wait: yes
        wait_timeout: 300
        tags:
          Name: bastion_host
          Project: vprofile
          Owner: Devops Team
        exact_count: 1
        security_group: "{{BastionSG_out.group_id}}"
        vpc_subnet_id: "{{pubsub1id}}"
      register: bastionhost_out
    - name: Insert/Update "BastionSGid" in vars/output_vars
      blockinfile:
        path: vars/output_vars
        backup: yes
        block: |
          BastionSGid: {{BastionSG_out.group_id}}





