---
- name: Install Erlang and RabbitMQ
  hosts: localhost
  become: yes
  tasks:
    - name: Install Erlang from the default repository
      apt:
        name: erlang
        state: present
        

    - name: Install RabbitMQ from the default repository
      apt:
        name: rabbitmq-server
        state: present
        update_cache: yes
    - name: Start & Enable RMQ
      service:
        name: rabbitmq-server
        state: started
        enabled: yes
      tags:
        - svc
    - name: Config setup
      copy:
        content: |
          [{rabbit, [{loopback_users, []}]}].
        dest: /etc/rabbitmq/rabbitmq.config
      notify:
        - Restart RMQ
      tags:
        - conf
    - rabbitmq_user:
        user: test
        password: test
        configure_priv: .*
        read_priv: .*
        write_priv: .*
        tags:
          - administrator
        state: present
      notify:
        - Restart RMQ
      tags:
        - conf
    - name: Enables the rabbitmq_management plugin
      rabbitmq_plugin:
        name: rabbitmq_management
        state: enabled
      notify:
        - Restart RMQ
      tags:
        - package

  handlers:
    - name: Restart RMQ
      service:
        name: rabbitmq-server
        state: daemon-reloaded


